### ISSUE TITLE
Redirect https://admidio.org to https://www.admidio.org/

### ISSUE THREAD

**Issue by ximex** [Admidio/website#10]
Use only one url als the correct url

**Comment by Fasse** [comment]
I tried a redirect with htaccess but then also our subdomains https://forum.admidio.org are redirected to https://www.forum.admidio.org

Do you have a better solution?

**Comment by ximex** [comment]
Forum link is  also `https://www.admidio.org/forum/` which link is the right one?

**Comment by Fasse** [comment]
Done, I have removed the subdomains.
