### ISSUE TITLE
Link to profile in forum wont work

### ISSUE THREAD

**Issue by Fasse** [Admidio/website#13]
If you have a login and then want to click on the profile icon upper right this wont work. Other links in the menu still work.

**Comment by Fasse** [comment]
@ximex do you have an idea why this link wont work? Left click "Open in new tab" still works.

**Comment by ximex** [comment]
the html code looks like if this button is a dropdown menu without items and the other buttons are simple links

**Comment by ximex** [comment]
@Fasse it looks like that all dropdown menues didn't work. There are more if you have a mobile layout

**Comment by Fasse** [comment]
Problem is now fixed. Made some changes to bootstrap.css
