### ISSUE TITLE
Change blue selection color with #349AAA

### ISSUE THREAD

**Issue by ximex** [Admidio/website#15]
![bildschirmfoto von 2016-10-10 22-07-54](https://cloud.githubusercontent.com/assets/1078640/19249472/0a6e24ce-8f36-11e6-84ef-e7cfe77d153a.png)

**Comment by Fasse** [comment]
This is fixed, now.

**Comment by ximex** [comment]
@Fasse there is no more selection color

**Comment by Fasse** [comment]
I don't know when this color is shown. As you can see in your screenshot, the selected entry is not the one you will see.

**Comment by ximex** [comment]
i see. this is another problem...

**Comment by ximex** [comment]
it's the `active` class that is set on the `li.level1` element
